# Generated by Django 3.2.9 on 2021-12-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=50)),
                ('Nature_of_Incidence', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=6)),
                ('Message', models.TextField(max_length=5000)),
                ('ip', models.CharField(max_length=20)),
            ],
        ),
    ]
