# Generated by Django 3.2.9 on 2021-12-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20211207_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_field', models.UUIDField()),
            ],
        ),
    ]
