# Generated by Django 3.2.9 on 2021-12-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_alter_tipoffmodel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoffModel',
        ),
    ]
