# Generated by Django 3.2.9 on 2021-12-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_auto_20211209_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoff',
            name='Mother_Tongue',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
