# Generated by Django 3.2.9 on 2021-12-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_tipoff_mother_tongue'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoff',
            name='Existing_or_Other',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
