# Generated by Django 3.2.9 on 2021-12-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_auto_20211210_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoff',
            name='File_Uploaded',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
