# Generated by Django 3.2.9 on 2021-12-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_tipoff_file_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoff',
            name='File_Uploaded',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
